# Generated by Django 5.1.1 on 2025-10-26 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название камеры')),
                ('camera_url', models.URLField(blank=True, null=True, verbose_name='ссылка на камеру')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец камеры')),
            ],
            options={
                'verbose_name': 'камера',
                'verbose_name_plural': 'камеры',
            },
        ),
    ]
